from __future__ import annotations
__all__ = ['KernelCanvas2']
class KernelCanvas2:
    def __init__(self, dimensions: tuple[int, int], numberOfKernels: int, bitsPerKernel: int = 1, activationDegree: float = 0.07) -> None:
        ...
    def getClosestKernel(self) -> list[list[int]]:
        ...
    def getKernelPoints(self) -> list[tuple[int, int]]:
        ...
    def transform(self, arg0: list[list[float]]) -> list[int]:
        ...
    def tst(self) -> None:
        ...
